version: '3'
services:
  backend:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
        - DB_HOST=db
        - DB_PORT=${DB_PORT}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_NAME=${DB_NAME}
  frontend:
    build: ./dashboard
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NODE_ENV=${NODE_ENV}
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
volumes:
  db:
    driver: local